### ISSUE TITLE
My LiveTV no longer imports the IPTV channels

### ISSUE THREAD

**Issue by samg80** [iptv-org/iptv-org.github.io#10]
I noticed the repository for the iptv-github.io is no longer importing the channels I had before. I noticed it was taken down by github. Is it going to be  re-enabled? if not is there an alternative? I really liked those publicly available channels

**Comment by boeder8** [comment]
The repo owners/contributors are waiting for a response from GitHub. Updates will be provided here 

https://github.com/iptv-org/iptv-org.github.io/issues/9#issue-1584162039

**Comment by samg80** [comment]
@freearhey why did you close the case if the issue has not been resolved? I'd like to track this case until the issue is resolved.

**Comment by freearhey** [comment]
@samg80 you can still follow this case by subscribing to the thread mentioned above by @boeder8.
