### ISSUE TITLE
m3u8 link for SSPlay APP

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv-org.github.io#1720]
### Discussed in https://github.com/orgs/iptv-org/discussions/1719

<div type='discussions-op-text'>

<sup>Originally posted by **sunyuanzhe** March 30, 2024</sup>
I want to use SSplay APP for watching livestream for Maldives TV Channel,Is there  anybody to extract livestream link for SSPlay APP?</div>

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
