### ISSUE TITLE
IPTV Link search

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv-org.github.io#1722]
### Discussed in https://github.com/orgs/iptv-org/discussions/1721

<div type='discussions-op-text'>

<sup>Originally posted by **sunyuanzhe** March 30, 2024</sup>
I've found a new website for searching livestreams
http://tonkiang.us/hoteliptv.php</div>

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
