### ISSUE TITLE
Channel Request: Yes TV Maldives

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv-org.github.io#1723]
### Discussed in https://github.com/orgs/iptv-org/discussions/1714

<div type='discussions-op-text'>

<sup>Originally posted by **sunyuanzhe** March 27, 2024</sup>
Any m3u8 link for Yes TV maldives? as the original stram link gets a 404 error</div>

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
