### ISSUE TITLE
Channel Request: ERI-TV and ERI-TV2

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv-org.github.io#1725]
### Discussed in https://github.com/orgs/iptv-org/discussions/1724

<div type='discussions-op-text'>

<sup>Originally posted by **sunyuanzhe** March 30, 2024</sup>
I want to use this subscription from denden media unfortunately my PalPal account is not available,is there somebody extracting stream link from them?</div>

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
