### ISSUE TITLE
RTNB burundi live stream

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv-org.github.io#1726]
### Discussed in https://github.com/orgs/iptv-org/discussions/1663

<div type='discussions-op-text'>

<sup>Originally posted by **sunyuanzhe** March  2, 2024</sup>
mms://41.79.226.194:8081
This stream uses MMS protocol does anybody convert this mms into a m3u8 link?</div>

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
