### ISSUE TITLE
Somali TV Livestream

### ISSUE THREAD

**Issue by sunyuanzhe** [iptv-org/iptv-org.github.io#1735]
### Discussed in https://github.com/orgs/iptv-org/discussions/1734

<div type='discussions-op-text'>

<sup>Originally posted by **sunyuanzhe** April  5, 2024</sup>
I found an APP called IQPlay, I've looked to the source code of this APP but found no m3u8 links,Is there anybody help finding them under 	https://ap02.iqplay.tv:8082/iqb8002/?/playlist.m3u8?</div>

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
