### ISSUE TITLE
I.Sat

### ISSUE THREAD

**Issue by ChristopherEccleston2024** [iptv-org/iptv-org.github.io#1744]
### Discussed in https://github.com/orgs/iptv-org/discussions/1737

<div type='discussions-op-text'>

<sup>Originally posted by **ChristopherEccleston2024** April  6, 2024</sup>
I was looking for a livestream for I.Sat Except For Others Like Investigation Discovery (Brazil), Is there anybody to extract a stream link from a satellite provider or something like that, please?</div>

**Comment by ChristopherEccleston2024** [comment]
we needed your help

**Comment by ChristopherEccleston2024** [comment]
i.sat is brazillian channel

**Comment by ChristopherEccleston2024** [comment]
latam closed transmission of i.sat

**Comment by ChristopherEccleston2024** [comment]
so... yes

**Comment by ChristopherEccleston2024** [comment]
Except Brazil

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
