### ISSUE TITLE
Space (Brazil)

### ISSUE THREAD

**Issue by ChristopherEccleston2024** [iptv-org/iptv-org.github.io#1746]
### Discussed in https://github.com/orgs/iptv-org/discussions/1736

<div type='discussions-op-text'>

<sup>Originally posted by **ChristopherEccleston2024** April  6, 2024</sup>
A very good, action oriented channel with brazillian movies and brazillian series: Space (Brazil) Just a Modern Channel

Any stream please?

Regards. 

Plus FULL HD
</div>

**Comment by vishveshjain** [comment]
Don't worry i found the steam link and i'll work on this. For now i am giving you stream link. Use that link in any IPTV or VLC stream.
http://tv.fuxxionpro.online:8080/Mar12334GFGFSDrddklqkd123/paD7AGyaLj/368478#checkedby:alliptvlinks.com

**Comment by vishveshjain** [comment]
I have added pull request regarding this. This channel will add soon.

**Comment by ChristopherEccleston2024** [comment]
Also Add Second Audio Program To This Brazilian Channel Please

**Comment by ChristopherEccleston2024** [comment]
As Soon as Possible

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
