### ISSUE TITLE
DHE (USA)

### ISSUE THREAD

**Issue by ChristopherEccleston2024** [iptv-org/iptv-org.github.io#1755]
### Discussed in https://github.com/orgs/iptv-org/discussions/1743

<div type='discussions-op-text'>

<sup>Originally posted by **ChristopherEccleston2024** April 11, 2024</sup>
A Very Good American channel with All Movies: DHE (USA)

Any Stream URL Please

Regards.

Plus English Audio

And Full HD

HD+</div>

**Comment by ChristopherEccleston2024** [comment]
Secondary Audio Program

**Comment by ChristopherEccleston2024** [comment]
And A Stream URL Please It's Full HD

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
