### ISSUE TITLE
Channel Request: Warner Channel South

### ISSUE THREAD

**Issue by ChristopherEccleston2024** [iptv-org/iptv-org.github.io#1757]
### Discussed in https://github.com/orgs/iptv-org/discussions/1756

<div type='discussions-op-text'>

<sup>Originally posted by **ChristopherEccleston2024** May  1, 2024</sup>
Stream URL For Warner Channel South Please Plus Second Audio Program</div>

**Comment by ChristopherEccleston2024** [comment]
Please

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
