### ISSUE TITLE
Channel Request: A&E (Mexico)

### ISSUE THREAD

**Issue by ChristopherEccleston2024** [iptv-org/iptv-org.github.io#1758]
### Discussed in https://github.com/orgs/iptv-org/discussions/1745

<div type='discussions-op-text'>

<sup>Originally posted by **ChristopherEccleston2024** April 11, 2024</sup>
Any m3u8 Link For A&E (Mexico) as the stream for the following website has been disabled:
no photos sorry</div>

**Comment by ChristopherEccleston2024** [comment]
Please Plus Second Audio Programme

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
