### ISSUE TITLE
Channel Request: Global TV (Peru)

### ISSUE THREAD

**Issue by ChristopherEccleston2024** [iptv-org/iptv-org.github.io#1759]
### Discussed in https://github.com/orgs/iptv-org/discussions/1747

<div type='discussions-op-text'>

<sup>Originally posted by **ChristopherEccleston2024** April 12, 2024</sup>
Any m3u8 Link For Global TV (Peru) anyone please</div>

**Comment by PopeyeTheSai10r** [comment]
Channel discussions should continue to be in https://github.com/orgs/iptv-org/discussions
