### ISSUE TITLE
Channel Request:ANIMESTATION (Argentina)

### ISSUE THREAD

**Issue by ChrisNolan202020202** [iptv-org/iptv-org.github.io#1780]
### Discussed in https://github.com/orgs/iptv-org/discussions/1779

<div type='discussions-op-text'>

<sup>Originally posted by **ChristopherEccleston2024** May 14, 2024</sup>
Stream URL For ANIMESTATION (Argentina) Plus Secondary Audio Programming</div>
Please

**Comment by PopeyeTheSai10r** [comment]
Channel requests should remain in Discussion until a stream url is found.
