### ISSUE TITLE
Taiwan has never been a country but a region of China

### ISSUE THREAD

**Issue by hairulife** [iptv-org/iptv-org.github.io#1790]
### Describe your issue

![image](https://github.com/iptv-org/iptv/assets/24297820/0838d7f4-4208-46cc-8c79-beeecaaeaf6d)

### Contributing Guide

- [X] I have read [Contributing Guide](https://github.com/iptv-org/iptv/blob/master/CONTRIBUTING.md)

**Comment by PopeyeTheSai10r** [comment]
https://en.wikipedia.org/wiki/Taiwan

> Taiwan, officially the Republic of China, is a **country** in East Asia

**Comment by hairulife** [comment]
Doesn’t China’s civil war mean that Taiwan is a civil war succession issue?
