### ISSUE TITLE
Chaines IPTV liens avec kodi ou autre

### ISSUE THREAD

**Issue by patf1966** [iptv-org/iptv-org.github.io#1938]
Bonjour à tous,

Je viens d'acheter une nokia box 8000 et je recherche comment utiliser une liste m3u avec kodi ou autre. J'ai un port usb pour le stockage des fichiers m3u. 

Merci pour votre retour et si vous voulez d'autres infos je suis à dispo.

Bonne journée et à plus :)

**Comment by BellezaEmporium** [comment]
Bonjour,

Ce n'est pas le bon endroit pour demander ce type de choses, nous parlons ici du site "iptv-org.github.io" qui référence la base de données du site, et non pas les chaînes que nous possédons, qui sont cette fois sur "iptv-org/iptv".
