### ISSUE TITLE
Few channels do not work properly 

### ISSUE THREAD

**Issue by samg80** [iptv-org/iptv-org.github.io#22]
Glad the IPTV is back. I am having issues with the following channels, they either do not play or if they play, they buffer every few seconds, other channels are working properly: 
Note: All these channels are available on the public domain
- https://www.alsharqiya.com/en/sharqiya-news-live/39846ee7-9408-4c75-88af-98c9eb8c3335
- https://imn.iq/
- https://www.nrttv.com/streamNRT.aspx

**Comment by freearhey** [comment]
Please use this form instead: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=%F0%9F%9B%A0+broken+stream&template=-----broken-stream.yml&title=Replace%3A+
