### ISSUE TITLE
iptv-restream/iptv-channels: Collection of 6000+ free IPTV channels from all over the world

### ISSUE THREAD

**Issue by Araaaa445** [iptv-org/iptv-org.github.io#8]
Skip to content

Pulls
Issues
Codespaces
Marketplace
Explore
 
 
iptv-restream
/
iptv-channels
Public
forked from yayanheeh/iptv
 Watch 195 
Fork 10.5kFork your own copy of iptv-restream/iptv-channels
 Starred 1.3k
Code
Pull requests
5
Actions
Projects
Security
Insights
iptv-restream/iptv-channels
 master 
Go to file
Add file
 Code
This branch is 5598 commits ahead of yayanheeh:master.
Latest commit

eldorplus Merge pull request #6 from iptv-restream/bot-patch-395aa4c
…
on Apr 6, 2022
Git stats
 5,691
Files
Type
Name
Latest commit message
Commit time
.github
Update CONTRIBUTING.md
2 years ago
.readme
Update README.md
2 years ago
channels
Merge pull request #6 from iptv-restream/bot-patch-395aa4c
9 months ago
scripts
Exclude timed out links from logs
2 years ago
.gitignore
Update gitignore
3 years ago
LICENSE
Rename LICENSE.md to LICENSE
3 years ago
README.md
Update README.md
2 years ago
index.m3u
Update index.m3u
3 years ago
package-lock.json
Installed iptv-checker-module package
2 years ago
package.json
Installed iptv-checker-module package
2 years ago
README.md
IPTV
Collection of 8000+ publicly available IPTV channels from all over the world.

Internet Protocol television (IPTV) is the delivery of television content over Internet Protocol (IP) networks.

Usage
To watch IPTV you just need to paste this link https://iptv-org.github.io/iptv/index.m3u to any player with support M3U-playlists.

Also you can instead use one of these playlists:

https://iptv-org.github.io/iptv/index.country.m3u (grouped by country)
https://iptv-org.github.io/iptv/index.category.m3u (grouped by category)
https://iptv-org.github.io/iptv/index.language.m3u (grouped by language)
Or select one of the playlists from the list below.

Playlists by category
Category	Channels	Playlist
Auto	2	https://iptv-org.github.io/iptv/categories/auto.m3u
Business	33	https://iptv-org.github.io/iptv/categories/business.m3u
Comedy	3	https://iptv-org.github.io/iptv/categories/comedy.m3u
Documentary	17	https://iptv-org.github.io/iptv/categories/documentary.m3u
Education	34	https://iptv-org.github.io/iptv/categories/education.m3u
Entertainment	67	https://iptv-org.github.io/iptv/categories/entertainment.m3u
Family	6	https://iptv-org.github.io/iptv/categories/family.m3u
Fashion	21	https://iptv-org.github.io/iptv/categories/fashion.m3u
Food	1	https://iptv-org.github.io/iptv/categories/food.m3u
General	124	https://iptv-org.github.io/iptv/categories/general.m3u
Health	2	https://iptv-org.github.io/iptv/categories/health.m3u
History	3	https://iptv-org.github.io/iptv/categories/history.m3u
Hobby	7	https://iptv-org.github.io/iptv/categories/hobby.m3u
Kids	75	https://iptv-org.github.io/iptv/categories/kids.m3u
Legislative	25	https://iptv-org.github.io/iptv/categories/legislative.m3u
Lifestyle	4	https://iptv-org.github.io/iptv/categories/lifestyle.m3u
Local	237	https://iptv-org.github.io/iptv/categories/local.m3u
Movies	56	https://iptv-org.github.io/iptv/categories/movies.m3u
Music	158	https://iptv-org.github.io/iptv/categories/music.m3u
News	230	https://iptv-org.github.io/iptv/categories/news.m3u
Religious	179	https://iptv-org.github.io/iptv/categories/religious.m3u
Shop	30	https://iptv-org.github.io/iptv/categories/shop.m3u
Sport	111	https://iptv-org.github.io/iptv/categories/sport.m3u
Travel	8	https://iptv-org.github.io/iptv/categories/travel.m3u
Weather	5	https://iptv-org.github.io/iptv/categories/weather.m3u
XXX	45	https://iptv-org.github.io/iptv/categories/xxx.m3u
Other	3021	https://iptv-org.github.io/iptv/categories/other.m3u
Playlists by language
Language	Channels	Playlist
Akan	2	https://iptv-org.github.io/iptv/languages/aka.m3u
Albanian	22	https://iptv-org.github.io/iptv/languages/sqi.m3u
Amharic	1	https://iptv-org.github.io/iptv/languages/amh.m3u
Arabic	271	https://iptv-org.github.io/iptv/languages/ara.m3u
Armenian	8	https://iptv-org.github.io/iptv/languages/hye.m3u
Azerbaijani	12	https://iptv-org.github.io/iptv/languages/aze.m3u
Bengali	5	https://iptv-org.github.io/iptv/languages/ben.m3u
Bosnian	3	https://iptv-org.github.io/iptv/languages/bos.m3u
Bulgarian	16	https://iptv-org.github.io/iptv/languages/bul.m3u
Burmese	16	https://iptv-org.github.io/iptv/languages/mya.m3u
Catalan	2	https://iptv-org.github.io/iptv/languages/cat.m3u
Chinese	1102	https://iptv-org.github.io/iptv/languages/zho.m3u
Croatian	14	https://iptv-org.github.io/iptv/languages/hrv.m3u
Czech	18	https://iptv-org.github.io/iptv/languages/ces.m3u
Danish	14	https://iptv-org.github.io/iptv/languages/dan.m3u
Dutch	66	https://iptv-org.github.io/iptv/languages/nld.m3u
English	562	https://iptv-org.github.io/iptv/languages/eng.m3u
Estonian	3	https://iptv-org.github.io/iptv/languages/est.m3u
Faroese	1	https://iptv-org.github.io/iptv/languages/fao.m3u
Finnish	3	https://iptv-org.github.io/iptv/languages/fin.m3u
French	80	https://iptv-org.github.io/iptv/languages/fra.m3u
Galician	2	https://iptv-org.github.io/iptv/languages/glg.m3u
Georgian	41	https://iptv-org.github.io/iptv/languages/kat.m3u
German	192	https://iptv-org.github.io/iptv/languages/deu.m3u
Hebrew	15	https://iptv-org.github.io/iptv/languages/heb.m3u
Hindi	131	https://iptv-org.github.io/iptv/languages/hin.m3u
Hungarian	18	https://iptv-org.github.io/iptv/languages/hun.m3u
Icelandic	3	https://iptv-org.github.io/iptv/languages/isl.m3u
Indonesian	47	https://iptv-org.github.io/iptv/languages/ind.m3u
Italian	142	https://iptv-org.github.io/iptv/languages/ita.m3u
Japanese	15	https://iptv-org.github.io/iptv/languages/jpn.m3u
Javanese	3	https://iptv-org.github.io/iptv/languages/jav.m3u
Kazakh	21	https://iptv-org.github.io/iptv/languages/kaz.m3u
Khmer	6	https://iptv-org.github.io/iptv/languages/khm.m3u
Kinyarwanda	5	https://iptv-org.github.io/iptv/languages/kin.m3u
Korean	31	https://iptv-org.github.io/iptv/languages/kor.m3u
Kurdish	6	https://iptv-org.github.io/iptv/languages/kur.m3u
Lao	4	https://iptv-org.github.io/iptv/languages/lao.m3u
Latvian	4	https://iptv-org.github.io/iptv/languages/lav.m3u
Luxembourgish	2	https://iptv-org.github.io/iptv/languages/ltz.m3u
Macedonian	5	https://iptv-org.github.io/iptv/languages/mkd.m3u
Mandarin Chinese	176	https://iptv-org.github.io/iptv/languages/cmn.m3u
Min Nan Chinese	2	https://iptv-org.github.io/iptv/languages/nan.m3u
Mongolian	6	https://iptv-org.github.io/iptv/languages/mon.m3u
Norwegian Bokmål	2	https://iptv-org.github.io/iptv/languages/nob.m3u
Persian	86	https://iptv-org.github.io/iptv/languages/fas.m3u
Polish	9	https://iptv-org.github.io/iptv/languages/pol.m3u
Portuguese	152	https://iptv-org.github.io/iptv/languages/por.m3u
Pushto	6	https://iptv-org.github.io/iptv/languages/pus.m3u
Romanian	89	https://iptv-org.github.io/iptv/languages/ron.m3u
Russian	251	https://iptv-org.github.io/iptv/languages/rus.m3u
Serbian	12	https://iptv-org.github.io/iptv/languages/srp.m3u
Sinhala	4	https://iptv-org.github.io/iptv/languages/sin.m3u
Slovak	34	https://iptv-org.github.io/iptv/languages/slk.m3u
Somali	1	https://iptv-org.github.io/iptv/languages/som.m3u
Spanish	342	https://iptv-org.github.io/iptv/languages/spa.m3u
Swedish	11	https://iptv-org.github.io/iptv/languages/swe.m3u
Tagalog	9	https://iptv-org.github.io/iptv/languages/tgl.m3u
Tamil	15	https://iptv-org.github.io/iptv/languages/tam.m3u
Thai	44	https://iptv-org.github.io/iptv/languages/tha.m3u
Turkish	69	https://iptv-org.github.io/iptv/languages/tur.m3u
Turkmen	11	https://iptv-org.github.io/iptv/languages/tuk.m3u
Ukrainian	159	https://iptv-org.github.io/iptv/languages/ukr.m3u
Urdu	23	https://iptv-org.github.io/iptv/languages/urd.m3u
Vietnamese	67	https://iptv-org.github.io/iptv/languages/vie.m3u
Yue Chinese	13	https://iptv-org.github.io/iptv/languages/yue.m3u
Undefined	191	https://iptv-org.github.io/iptv/languages/undefined.m3u
Playlists by country
Country	Channels	Playlist	EPG
 Afghanistan	6	https://iptv-org.github.io/iptv/countries/af.m3u	
 Albania	15	https://iptv-org.github.io/iptv/countries/al.m3u	
 Algeria	2	https://iptv-org.github.io/iptv/countries/dz.m3u	
 Andorra	2	https://iptv-org.github.io/iptv/countries/ad.m3u	
 Angola	1	https://iptv-org.github.io/iptv/countries/ao.m3u	
 Argentina	46	https://iptv-org.github.io/iptv/countries/ar.m3u	
 Armenia	8	https://iptv-org.github.io/iptv/countries/am.m3u	
 Aruba	3	https://iptv-org.github.io/iptv/countries/aw.m3u	
 Australia	15	https://iptv-org.github.io/iptv/countries/au.m3u	http://i.mjh.nz/nzau/epg.xml.gz
 Austria	16	https://iptv-org.github.io/iptv/countries/at.m3u	http://epg.streamstv.me/epg/guide-austria.xml.gz
 Azerbaijan	11	https://iptv-org.github.io/iptv/countries/az.m3u	https://iptvx.one/epg/epg.xml.gz
 Bahrain	8	https://iptv-org.github.io/iptv/countries/bh.m3u	
 Bangladesh	5	https://iptv-org.github.io/iptv/countries/bd.m3u	
 Barbados	1	https://iptv-org.github.io/iptv/countries/bb.m3u	
 Belarus	11	https://iptv-org.github.io/iptv/countries/by.m3u	https://iptvx.one/epg/epg.xml.gz
 Belgium	24	https://iptv-org.github.io/iptv/countries/be.m3u	
 Bolivia	10	https://iptv-org.github.io/iptv/countries/bo.m3u	
 Bosnia and Herzegovina	3	https://iptv-org.github.io/iptv/countries/ba.m3u	http://epg.streamstv.me/epg/guide-exyu.xml.gz
 Brazil	123	https://iptv-org.github.io/iptv/countries/br.m3u	
 Brunei	3	https://iptv-org.github.io/iptv/countries/bn.m3u	
 Bulgaria	16	https://iptv-org.github.io/iptv/countries/bg.m3u	
 Burkina Faso	1	https://iptv-org.github.io/iptv/countries/bf.m3u	
 Cambodia	6	https://iptv-org.github.io/iptv/countries/kh.m3u	
 Cameroon	5	https://iptv-org.github.io/iptv/countries/cm.m3u	
 Canada	30	https://iptv-org.github.io/iptv/countries/ca.m3u	http://epg.streamstv.me/epg/guide-canada.xml.gz
 Chile	39	https://iptv-org.github.io/iptv/countries/cl.m3u	
 China	1015	https://iptv-org.github.io/iptv/countries/cn.m3u	http://epg.51zmt.top:8000/e.xml.gz
 Colombia	20	https://iptv-org.github.io/iptv/countries/co.m3u	
 Costa Rica	9	https://iptv-org.github.io/iptv/countries/cr.m3u	
 Croatia	14	https://iptv-org.github.io/iptv/countries/hr.m3u	http://tvprofil.net/xmltv/data/epg_tvprofil.net.xml
 Curaçao	3	https://iptv-org.github.io/iptv/countries/cw.m3u	
 Cyprus	14	https://iptv-org.github.io/iptv/countries/cy.m3u	
 Czech Republic	18	https://iptv-org.github.io/iptv/countries/cz.m3u	http://epg.streamstv.me/epg/guide-cz.xml.gz
 Democratic Republic of the Congo	1	https://iptv-org.github.io/iptv/countries/cd.m3u	
 Denmark	14	https://iptv-org.github.io/iptv/countries/dk.m3u	
 Dominican Republic	25	https://iptv-org.github.io/iptv/countries/do.m3u	
 Ecuador	8	https://iptv-org.github.io/iptv/countries/ec.m3u	
 Egypt	8	https://iptv-org.github.io/iptv/countries/eg.m3u	
 El Salvador	2	https://iptv-org.github.io/iptv/countries/sv.m3u	
 Equatorial Guinea	1	https://iptv-org.github.io/iptv/countries/gq.m3u	
 Estonia	3	https://iptv-org.github.io/iptv/countries/ee.m3u	
 Ethiopia	1	https://iptv-org.github.io/iptv/countries/et.m3u	
 Faroe Islands	1	https://iptv-org.github.io/iptv/countries/fo.m3u	
 Finland	3	https://iptv-org.github.io/iptv/countries/fi.m3u	
 Fiji	1	https://iptv-org.github.io/iptv/countries/fj.m3u	
 France	59	https://iptv-org.github.io/iptv/countries/fr.m3u	
 Gambia	1	https://iptv-org.github.io/iptv/countries/gm.m3u	
 Georgia	41	https://iptv-org.github.io/iptv/countries/ge.m3u	
 Germany	160	https://iptv-org.github.io/iptv/countries/de.m3u	
 Ghana	3	https://iptv-org.github.io/iptv/countries/gh.m3u	
 Greece	55	https://iptv-org.github.io/iptv/countries/gr.m3u	
 Guadeloupe	1	https://iptv-org.github.io/iptv/countries/gp.m3u	
 Guyana	2	https://iptv-org.github.io/iptv/countries/gy.m3u	
 Haiti	8	https://iptv-org.github.io/iptv/countries/ht.m3u	
 Honduras	17	https://iptv-org.github.io/iptv/countries/hn.m3u	
 Hong Kong	20	https://iptv-org.github.io/iptv/countries/hk.m3u	
 Hungary	18	https://iptv-org.github.io/iptv/countries/hu.m3u	http://epg.streamstv.me/epg/guide-hungry.xml.gz
 Iceland	3	https://iptv-org.github.io/iptv/countries/is.m3u	
 India	153	https://iptv-org.github.io/iptv/countries/in.m3u	http://epg.streamstv.me/epg/guide-india.xml.gz
 Indonesia	51	https://iptv-org.github.io/iptv/countries/id.m3u	
 International	75	https://iptv-org.github.io/iptv/countries/int.m3u	
 Iran	90	https://iptv-org.github.io/iptv/countries/ir.m3u	
 Iraq	33	https://iptv-org.github.io/iptv/countries/iq.m3u	
 Ireland	3	https://iptv-org.github.io/iptv/countries/ie.m3u	
 Israel	17	https://iptv-org.github.io/iptv/countries/il.m3u	http://epg.streamstv.me/epg/guide-israel.xml.gz
 Italy	142	https://iptv-org.github.io/iptv/countries/it.m3u	
 Ivory Coast	3	https://iptv-org.github.io/iptv/countries/ci.m3u	
 Jamaica	2	https://iptv-org.github.io/iptv/countries/jm.m3u	
 Japan	15	https://iptv-org.github.io/iptv/countries/jp.m3u	
 Jordan	7	https://iptv-org.github.io/iptv/countries/jo.m3u	
 Kazakhstan	24	https://iptv-org.github.io/iptv/countries/kz.m3u	https://iptvx.one/epg/epg.xml.gz
 Kenya	2	https://iptv-org.github.io/iptv/countries/ke.m3u	
 Kosovo	10	https://iptv-org.github.io/iptv/countries/xk.m3u	
 Kuwait	12	https://iptv-org.github.io/iptv/countries/kw.m3u	
 Kyrgyzstan	8	https://iptv-org.github.io/iptv/countries/kg.m3u	
 Laos	4	https://iptv-org.github.io/iptv/countries/la.m3u	
 Latvia	4	https://iptv-org.github.io/iptv/countries/lv.m3u	https://iptvx.one/epg/epg.xml.gz
 Lebanon	18	https://iptv-org.github.io/iptv/countries/lb.m3u	
 Libya	8	https://iptv-org.github.io/iptv/countries/ly.m3u	
 Liechtenstein	2	https://iptv-org.github.io/iptv/countries/li.m3u	
 Lithuania	1	https://iptv-org.github.io/iptv/countries/lt.m3u	https://iptvx.one/epg/epg.xml.gz
 Luxembourg	2	https://iptv-org.github.io/iptv/countries/lu.m3u	
 Macau	5	https://iptv-org.github.io/iptv/countries/mo.m3u	
 Malaysia	21	https://iptv-org.github.io/iptv/countries/my.m3u	https://freeview.github.io/iptv/epg/tv.xml
 Malta	1	https://iptv-org.github.io/iptv/countries/mt.m3u	http://epg.streamstv.me/epg/guide-malta.xml.gz
 Mexico	34	https://iptv-org.github.io/iptv/countries/mx.m3u	
 Moldova	15	https://iptv-org.github.io/iptv/countries/md.m3u	https://iptvx.one/epg/epg.xml.gz
 Mongolia	6	https://iptv-org.github.io/iptv/countries/mn.m3u	
 Montenegro	4	https://iptv-org.github.io/iptv/countries/me.m3u	
 Morocco	19	https://iptv-org.github.io/iptv/countries/ma.m3u	
 Mozambique	4	https://iptv-org.github.io/iptv/countries/mz.m3u	
 Myanmar	17	https://iptv-org.github.io/iptv/countries/mm.m3u	
 Nepal	8	https://iptv-org.github.io/iptv/countries/np.m3u	
 Netherlands	57	https://iptv-org.github.io/iptv/countries/nl.m3u	
 New Zealand	8	https://iptv-org.github.io/iptv/countries/nz.m3u	http://i.mjh.nz/nzau/epg.xml.gz
 Nicaragua	2	https://iptv-org.github.io/iptv/countries/ni.m3u	
 Nigeria	3	https://iptv-org.github.io/iptv/countries/ng.m3u	
 North Korea	1	https://iptv-org.github.io/iptv/countries/kp.m3u	
 North Macedonia	10	https://iptv-org.github.io/iptv/countries/mk.m3u	
 Norway	3	https://iptv-org.github.io/iptv/countries/no.m3u	http://epg.streamstv.me/epg/guide-norway.xml.gz
 Oman	5	https://iptv-org.github.io/iptv/countries/om.m3u	
 Pakistan	43	https://iptv-org.github.io/iptv/countries/pk.m3u	
 Palestine	11	https://iptv-org.github.io/iptv/countries/ps.m3u	
 Panama	4	https://iptv-org.github.io/iptv/countries/pa.m3u	
 Paraguay	2	https://iptv-org.github.io/iptv/countries/py.m3u	
 Peru	20	https://iptv-org.github.io/iptv/countries/pe.m3u	
 Philippines	11	https://iptv-org.github.io/iptv/countries/ph.m3u	
 Poland	9	https://iptv-org.github.io/iptv/countries/pl.m3u	
 Portugal	22	https://iptv-org.github.io/iptv/countries/pt.m3u	
 Puerto Rico	3	https://iptv-org.github.io/iptv/countries/pr.m3u	
 Qatar	12	https://iptv-org.github.io/iptv/countries/qa.m3u	
 Romania	76	https://iptv-org.github.io/iptv/countries/ro.m3u	
 Russia	236	https://iptv-org.github.io/iptv/countries/ru.m3u	https://iptvx.one/epg/epg.xml.gz
 Rwanda	5	https://iptv-org.github.io/iptv/countries/rw.m3u	
 Saint Kitts and Nevis	3	https://iptv-org.github.io/iptv/countries/kn.m3u	
 San Marino	1	https://iptv-org.github.io/iptv/countries/sm.m3u	
 Saudi Arabia	29	https://iptv-org.github.io/iptv/countries/sa.m3u	
 Senegal	1	https://iptv-org.github.io/iptv/countries/sn.m3u	
 Serbia	8	https://iptv-org.github.io/iptv/countries/rs.m3u	http://epg.streamstv.me/epg/guide-exyu.xml.gz
 Sierra Leone	1	https://iptv-org.github.io/iptv/countries/sl.m3u	
 Singapore	8	https://iptv-org.github.io/iptv/countries/sg.m3u	https://freeview.github.io/iptv/epg/tv.xml
 Slovakia	34	https://iptv-org.github.io/iptv/countries/sk.m3u	
 Slovenia	6	https://iptv-org.github.io/iptv/countries/si.m3u	
 Somalia	1	https://iptv-org.github.io/iptv/countries/so.m3u	
 South Africa	1	https://iptv-org.github.io/iptv/countries/za.m3u	http://i.mjh.nz/za/DStv/epg.xml.gz
 South Korea	29	https://iptv-org.github.io/iptv/countries/kr.m3u	
 Spain	94	https://iptv-org.github.io/iptv/countries/es.m3u	
 Sri Lanka	4	https://iptv-org.github.io/iptv/countries/lk.m3u	
 Sudan	7	https://iptv-org.github.io/iptv/countries/sd.m3u	
 Sweden	12	https://iptv-org.github.io/iptv/countries/se.m3u	
 Switzerland	21	https://iptv-org.github.io/iptv/countries/ch.m3u	
 Syria	19	https://iptv-org.github.io/iptv/countries/sy.m3u	
 Taiwan	69	https://iptv-org.github.io/iptv/countries/tw.m3u	
 Tajikistan	1	https://iptv-org.github.io/iptv/countries/tj.m3u	
 Tanzania	1	https://iptv-org.github.io/iptv/countries/tz.m3u	
 Thailand	46	https://iptv-org.github.io/iptv/countries/th.m3u	
 Trinidad and Tobago	1	https://iptv-org.github.io/iptv/countries/tt.m3u	
 Tunisia	3	https://iptv-org.github.io/iptv/countries/tn.m3u	
 Turkey	69	https://iptv-org.github.io/iptv/countries/tr.m3u	
 Turkmenistan	11	https://iptv-org.github.io/iptv/countries/tm.m3u	
 Uganda	1	https://iptv-org.github.io/iptv/countries/ug.m3u	
 Ukraine	159	https://iptv-org.github.io/iptv/countries/ua.m3u	https://iptvx.one/epg/epg.xml.gz
 United Arab Emirates	45	https://iptv-org.github.io/iptv/countries/ae.m3u	
 United Kingdom	36	https://iptv-org.github.io/iptv/countries/uk.m3u	
 United States	376	https://iptv-org.github.io/iptv/countries/us.m3u	http://epg.streamstv.me/epg/guide-usa.xml.gz
 Uruguay	4	https://iptv-org.github.io/iptv/countries/uy.m3u	
 Venezuela	2	https://iptv-org.github.io/iptv/countries/ve.m3u	
 Vietnam	67	https://iptv-org.github.io/iptv/countries/vn.m3u	
 Virgin Islands of the United States	1	https://iptv-org.github.io/iptv/countries/vi.m3u	
 Western Sahara	1	https://iptv-org.github.io/iptv/countries/eh.m3u	
 Yemen	10	https://iptv-org.github.io/iptv/countries/ye.m3u	
For Developers
In addition to the above methods, you can also get a list of all available channels in JSON format.

To do this, you just have to make a GET request to:

https://iptv-org.github.io/iptv/channels.json
If successful, you should get the following response:

[
  ...
  {
    "name": "CNN",
    "logo": "https://i.imgur.com/ilZJT5s.png",
    "url": "http://ott-cdn.ucom.am/s27/index.m3u8",
    "category": "News",
    "language": [
      {
        "code": "eng",
        "name": "English"
      }
    ],
    "country": {
      "code": "us",
      "name": "United States"
    },
    "tvg": {
      "id": "cnn.us",
      "name": "CNN",
      "url": "http://epg.streamstv.me/epg/guide-usa.xml.gz"
    }
  },
  ...
]
Resources
You can find links to various IPTV related resources in this repository iptv-org/awesome-iptv.

Contribution
Please make sure to read the Contributing Guide before making a pull request.

If you find an error or have any suggestions on how to organize a playlist, please send an issue.

About
Collection of 6000+ free IPTV channels from all over the world

Resources
 Readme
License
 Unlicense license
Code of conduct
 Code of conduct
Stars
 1.3k stars
Watchers
 195 watching
Forks
 10.5k forks
Releases
No releases published
Packages
No packages published
Languages
JavaScript
100.0%
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About

**Comment by Thdjjek** [comment]
Hi

**Comment by amir32** [comment]
🌍 Wow, this collection of 6000+ free IPTV channels from around the world is an impressive resource! 😲 As we explore the diverse offerings of the digital world, it's always fun to discover unique online tools. Speaking of which, if you're looking to add a bit of Pokémon-themed fun to your digital adventures, check out [fusioncalculator.com](https://fusioncalculator.com/). It's a fantastic Pokémon Fusion Calculator that lets you combine and create your own unique Pokémon creatures! 🧩🔥
